---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dino-park-ingress
  namespace: dino-park
spec:
  rules:
  - host: dinopark.mozilla.community
    http:
      paths:
      - path: /
        backend:
          serviceName: dino-park-front-end-service
          servicePort: 80
      - path: /graphql
        backend:
          serviceName: iam-profile-faker-service
          servicePort: 80
      - path: /orgchart
        backend:
          serviceName: dino-tree-service
          servicePort: 80
      - path: /admin/users
        backend:
          serviceName: dino-cave-service
          servicePort: 80
  - host: mozillians.mozilla.community
    http:
      paths:
      - path: /
        backend:
          serviceName: dino-park-mozillians-service
          servicePort: 80
